### ISSUE TITLE
Unable to see predefined_classes in data/ when compiled as .exe 

### ISSUE THREAD

**Issue by jinmingteo** [jinmingteo/labelImg_OBB#10]
#### Issue description
Upon compiling to an exe (be it one installer or with other packages, predefined_classes.txt are not mapped over;

![image](https://user-images.githubusercontent.com/28519525/129498674-a10389b1-600d-4ef1-afdd-7b8c3e470533.png)

#### Steps to reproduce the issue

1. Follow [here](https://github.com/jinmingteo/labelImg_OBB#exporting-to-windows)

#### What's the expected result?

- classes are loaded from data/predefined_classes.txt
![image](https://user-images.githubusercontent.com/28519525/129498782-7be51330-0ca2-4e20-806f-89faadbb918d.png)

**Comment by ernestlwt** [comment]
fix in https://github.com/jinmingteo/labelImg_OBB/commit/c55da04a5a08e05c54ccee081d2c4c83f43fcaff

please check.

apologies. accidentally commit into master directly
